[build]
  builder = "nixpacks"

[deploy]
  startCommand = "npm start"
  healthcheckPath = "/"
  healthcheckTimeout = 300
  restartPolicyType = "always"

[[services]]
  name = "web"
  
  [services.variables]
    NODE_ENV = "production"
